services:
  app:
    build: src/.
    ports:
      - "5000:5000"
    depends_on:
      - database
    restart: on-failure

  database:
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=1234
    image: 'postgres:14.1'
    restart: always
    volumes:
      - ./src/SeemsPhishy/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - database

