random_names = ("Mareike Omdahl",
"Seong-Su Polzin",
"Oskar Al-Ghazzawi",
"Jemima Vicente",
"Susanna Yamauchi",
"Adzo Snider",
"Georgios Yun",
"Askr Ogtrop",
"Winfrith McNeal",
"Vangelija Keller",
"Sven Bieber")